on:
  push:
    branches:
      - CI/CD_Setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v4

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: ðŸ“ Configure Git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: ðŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ðŸ“¦ Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "EXPO_PUBLIC_APP_VARIANT=client" >> $GITHUB_ENV
          echo "EXPO_USE_DEFAULT_LOCATION=true" >> $GITHUB_ENV
          echo "ENVIRONMENT_MODE=production" >> $GITHUB_ENV
          echo "EXPO_STORYBOOK=false" >> $GITHUB_ENV
          echo "EAS_BUILD_PROFILE=client-production" >> $GITHUB_ENV
          echo "EAS_PROJECT_ID=${{ secrets.CLIENT_APP_ID }}" >> $GITHUB_ENV

      - name: Check CLIENT_APP_ID
        run: |
          if [ -z "${{ secrets.CLIENT_APP_ID }}" ]; then
            echo "CLIENT_APP_ID is not set or is empty"
            exit 1
          else
            echo "CLIENT_APP_ID is set"
          fi

      - name: ðŸš€ Build app
        run: |
          eas build --platform ios --profile $EAS_BUILD_PROFILE --non-interactive
        env:
          EAS_BUILD_PROFILE: ${{ env.EAS_BUILD_PROFILE }}
